[phases.setup]
nixpkgs = ["python310", "nodejs_18"]

[phases.build]
cmds = [
    "cd backend && pip install -r requirements.txt",
    "cd frontend && npm install && npm run build"
]

[phases.start]
cmds = [
    "cd backend && python manage.py migrate",
    "cd backend && python manage.py collectstatic --noinput",
    "cd backend && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
]